apiVersion: v1
kind: Pod
metadata:
  labels:
    run: web-prod
    env: prod
    service: webserver
  name: web-prod
spec:
  containers:
  - image: ubuntu
    name: ubuntu
    command: ["/bin/bash"]
    args: ["-c", "tail -f /dev/null"]
    resources:
      limits:
        cpu: "1.5"
        memory: "128Mi"
      requests:
        cpu: "0.3"
        memory: "64Mi"        
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
