apiVersion: v1
kind: Pod
metadata:
  labels:
    run: web-stg
    env: prod
    service: webserver
  name: web-stg
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - mountPath: /giropops
      name: emptydir-volume
    resources:
      limits:
        cpu: "1"
        memory: "128Mi"
      requests:
        cpu: "0.5"
        memory: "64Mi"        
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: emptydir-volume
    emptyDir:
      sizeLimit: 256Mi
status: {}
