apiVersion: v1
kind: Service
metadata:
  name: nginx-laodbalancer
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
  - port: 80
    name: http
    targetPort: 80
