apiVersion: v1 
kind: PersistentVolume 
metadata: 
  name: meu-pv-nfs 
  labels:
    storage: nfs 
spec: 
  capacity: 
    storage: 1Gi 
  accessModes: 
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain 
  nfs: 
    server: 192.168.224.130
    path: "/mnt/nfs" 
  storageClassName: nfs 